# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from product_server.models.base_model_ import Model
from product_server import util


class Product(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, sku: str=None, brand: str=None, slug: str=None, title: str=None, quantity: int=None):  # noqa: E501
        """Product - a model defined in Swagger

        :param id: The id of this Product.  # noqa: E501
        :type id: int
        :param sku: The sku of this Product.  # noqa: E501
        :type sku: str
        :param brand: The brand of this Product.  # noqa: E501
        :type brand: str
        :param slug: The slug of this Product.  # noqa: E501
        :type slug: str
        :param title: The title of this Product.  # noqa: E501
        :type title: str
        :param quantity: The quantity of this Product.  # noqa: E501
        :type quantity: int
        """
        
        self.id = id
        self.sku = sku
        self.brand = brand
        self.slug = slug
        self.title = title
        self.quantity = quantity

        self.product_types = {
            'id': int,
            'sku': str,
            'brand': str,
            'slug': str,
            'title': str,
            'quantity': int
        }

        self.attribute_map = {
            'id': 'id',
            'sku': 'sku',
            'title': 'title',
            'brand': 'brand',
            'slug': 'slug',
            'quantity': 'quantity'
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Product':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product of this Product.  # noqa: E501
        :rtype: Product
        """
        return util.deserialize_model(dikt, cls)
